analytics: {}
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0
name: Patrick Dobbins
opengraph: {}
purpose:
  - name: engagement
typography_spectrum: 0.9356533922255039
